### ISSUE TITLE
I need some help!

### ISSUE THREAD

**Issue by craudilho1199** [Arhkei/Email-Spoofer#1]
Hi bro!
Can you please tell me your product is still working?
I've got a problem, screenshots is attached.
Please help me solve my problem if your product still works.
![Email-__________________NEW_syntax_error](https://user-images.githubusercontent.com/84741432/121346326-a642b400-c92e-11eb-9e7e-bf1f1390a523.PNG)
![Email-__________________NEW_syntax_error22222222222222222](https://user-images.githubusercontent.com/84741432/121346343-a9d63b00-c92e-11eb-9ef3-6261f36586fa.PNG)

sudo python3 mail.py
error as shown below
![Email-_________-3333333333333](https://user-images.githubusercontent.com/84741432/121347576-071ebc00-c930-11eb-9ca6-bb1dac112167.PNG)
![EMail-____________________4](https://user-images.githubusercontent.com/84741432/121347597-0c7c0680-c930-11eb-9882-4e3ce1c3e02e.PNG)

MY receiver_email DOMAIN different from the DOMAIN of mail.py ---> smtpObj = smtplib.SMTP('smtp.office365.com', 587)

**Comment by Arhkei** [comment]
Your first error was because you were using python  2 instead of python 3. The next error tells you that you need to use  STARTTLS. In the code on line 58 you can uncomment that to add the functionality.

**Comment by Arhkei** [comment]
prod.outlook.com is a part of Outlook. Your email goes through here first, it will still work fine.

**Comment by craudilho1199** [comment]
Please tell me how the successful letter in the terminal should look?

I changed the code, and now it looks like:
![777777777777777777777777777777777___________________________fdasfds213adsDSadDADaDAKLIUhnjkaIad](https://user-images.githubusercontent.com/84741432/121425562-373f7c80-c97b-11eb-9880-deb882f2ef88.PNG)


That's what it looks like in the terminal:
![88888888888888____________---dsaiuodasoidyausidyasi7d9isapkgtrloun hfaakbcvzmp DS](https://user-images.githubusercontent.com/84741432/121425594-4292a800-c97b-11eb-860a-58f3b9542371.PNG)


No mistakes in the terminal, but letters don't come, I've tried two different Email services, zero results.

I didn't quite understand if I should give the same name to the recipient's e-mail, that's in that line?

**Comment by Arhkei** [comment]
There's many reasons why the email could not be sending, but as far as the program is concerned that is what a successful letter should look like.

Possible reasons why they aren't sending

- The SMTP server is set up so it won't allow you to send as another user.
- The email is getting removed before it reaches the inbox by a spam filter
- The email is getting sent straight to spam
- The SMTP server doesn't allow you to use that account to send mail from a third-party program

You can comment out this line to ignore the PDF file it is trying to send as it's a test PDF file and may get picked up by the spam filter. (Once you comment out this line it reduces the output in the terminal ending at the HTML)
https://github.com/Arhkei/Email-Spoofer/blob/e1eb939ea1496f47aba408b90ef6987c78799cc5/mail.py#L52
You can also try writing more to see if that gets you pass the spam filter.

Do note that this is a proof-of-concept program, it was designed for a specific email server that allowed the sending of emails as other users. This can still work with an email server such as gmail, but if you don't have the send as permission then the email will contain the fake name but the email address will not be spoofed. You can set up your own email server and allow this for easier testing. I'll update the README with this information to further clarify it being a targeted tool rather than a general one.

> I didn't quite understand if I should give the same name to the recipient's e-mail, that's in that line?

I assume you mean this line?
https://github.com/Arhkei/Email-Spoofer/blob/e1eb939ea1496f47aba408b90ef6987c78799cc5/mail.py#L10

You can put whatever name you want, if you match the name with the proper name associated with the email you may also get their picture to show up (in my testing for a certain mail server, can't say which others it will work on).

Edit: I've uploaded a results.png to better explain what the ending email looks like in a vulnerable email server. The sender email and name can be whatever you'd like and the Microsoft profile picture came automatically.

**Comment by craudilho1199** [comment]
What should it look like a successful emails in the terminal window?
Show me please)

**Comment by Arhkei** [comment]
Your last picture is what a successful email looks like, this does not mean the person will receive the email, but it does mean the program ran without any errors.

**Comment by uoffice3** [comment]
I will like to inform you that I have a bank account in Australia, Malaysia, Indonesia, and Thailand for quick cash out. For invoice payment, bank wire transfers, or any payment form. If interested please let me know me. 

My tele is lion_omarion
